# spring
server:
 port: 8841
 servlet:
  context-path: /nacos
 tomcat:
  basedir: logs

nacos:
 cmdb:
  dumpTaskInterval: 3600
  eventTaskInterval: 10
  labelTaskInterval: 300
  loadDataAtStart: false
 security: # 删除此配置无需登录验证
  ignore:
   urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/login,/v1/console/health/**,/v1/cs/**,/v1/ns/**,/v1/cmdb/**,/actuator/**,/v1/console/server/**

spring:
 datasource:
  platform: mysql
 security:
  enabled: true

db:
 num: 1
 user: ${MYSQL-USER:root}
 password: ${MYSQL-PWD:root}
 url:
  0: jdbc:mysql://localhost:3306/nacosconfig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


# metrics for prometheus
#management.endpoints.web.exposure.include=*
# metrics for elastic search
#management.metrics.export.elastic.enabled=false
#management.metrics.export.elastic.host=http://localhost:9200
# metrics for influx
#management.metrics.export.influx.db=springboot
#management.metrics.export.influx.uri=http://localhost:8086
#management.metrics.export.influx.auto-create-db=true
#management.metrics.export.influx.consistency=one
#management.metrics.export.influx.compressed=true
# default current work dir
#server.tomcat.basedir=
## spring security config
### turn off security
#spring.security.enabled=false
#management.security=false
#security.basic.enabled=false
#nacos.security.ignore.urls=/**
