# 集群配置
spring:
  application:
    name: eureka-server-cluster

---
server:
  port: 8761
  profiles: peer1
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    hostname: peer1

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
  instance:
    hostname: peer2

---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    hostname: peer3

