server:
  port: 8001

spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8841,localhost:8842,localhost:8843


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

